version: "3"

services:
  nginx:
    image: fabrik/docker-eshop/nginx
    restart: unless-stopped
    volumes:
      - ./:/srv/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - docker-eshop
  phpfpm:
    image: fabrik/docker-eshop/php
    restart: unless-stopped
    volumes:
      - ./:/srv/www
    networks:
      - docker-eshop
  mariadb:
    image: mariadb
    restart: unless-stopped
    volumes:
    - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dbPassword
    networks:
      - docker-eshop

networks:
  docker-eshop:
